[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"
